[package]
name = "qiyana0"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nonprivate_server"
path = "src/nonprivate/nonprivate_server.rs"
test = false

[[bin]]
name = "nonprivate_client"
path = "src/nonprivate/nonprivate_client.rs"
test = false

[[bin]]
name = "baseline_server"
path = "src/baseline/baseline_server.rs"
test = false

[[bin]]
name = "baseline_client"
path = "src/baseline/baseline_client.rs"
test = false

[[bin]]
name = "baselineh_server"
path = "src/baselineh/baselineh_server.rs"
test = false

[[bin]]
name = "baselineh_client"
path = "src/baselineh/baselineh_client.rs"
test = false

[[bin]]
name = "qiyana1_server"
path = "src/qiyana1/qiyana1_server.rs"
test = false

[[bin]]
name = "qiyana1_client"
path = "src/qiyana1/qiyana1_client.rs"
test = false

[[bin]]
name = "qiyana0_server"
path = "src/qiyana0/qiyana0_server.rs"
test = false

[[bin]]
name = "qiyana0_client"
path = "src/qiyana0/qiyana0_client.rs"
test = false

[[bin]]
name = "baselineclient"
path = "src/baseline/client.rs"
test = false

[[bin]]
name = "baselinemaster"
path = "src/baseline/master.rs"
test = false

[[bin]]
name = "baselineworker"
path = "src/baseline/worker.rs"
test = false

[[bin]]
name = "baselinehclient"
path = "src/baselineh/client.rs"
test = false

[[bin]]
name = "baselinehmaster"
path = "src/baselineh/master.rs"
test = false

[[bin]]
name = "baselinehworker"
path = "src/baselineh/worker.rs"
test = false

[[bin]]
name = "qiyana0client"
path = "src/qiyana0/client.rs"
test = false

[[bin]]
name = "qiyana0master"
path = "src/qiyana0/master.rs"
test = false

[[bin]]
name = "qiyana0worker"
path = "src/qiyana0/worker.rs"
test = false

[[bin]]
name = "qiyana1client"
path = "src/qiyana1/client.rs"
test = false

[[bin]]
name = "qiyana1master"
path = "src/qiyana1/master.rs"
test = false

[[bin]]
name = "qiyana1worker"
path = "src/qiyana1/worker.rs"
test = false

[dependencies]
tfhe = { version = "1.5.1", features = ["boolean", "shortint", "integer", "strings"] }
rayon = "1.11.0"
bincode = "1.3.3"
rand = "0.8.5"
itertools = "0.10.5"
crossbeam = "0.8.4"
rand_chacha = "0.3.1"
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
futures = "0.3.31"
sha2 = "0.10"
